---
title: "README"
author: "June Grimes"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mandibular Morphovariation Project
This repo contains information on how small mammals' evolutionary response can allow them to persist in a changing landscape. It's part of a greater project looking at how evolutionary and plastic response work in parallel and/or independently to help buffer speciation. 

Landmarking coordinates for each species can be found in the [data folder](https://github.com/Juniper41/mandibular_morphovariation/tree/main/data)

## Study Systems
This project looks at morphological variation of small mammal dentary bones from Two Ledges Chamber, NV and Homestead Cave, UT over the last ~10,000 years. This is just one of the proxies at understanding how small mammals adapt to a changing landscape. 

The two systems have different anthropogenic histories and resource bases. 

## Broken Links

_If you find a broken link or corrupt file, please create an issue to let me know!_


## Temporal Scale

|Stratum|Two Ledges (ybp)|Homestead (ybp)|
:--|:--|:--|
|1|Modern|Modern|
|2|288|150|
|3|317|930|
|4|884|1095|
|5|1709|3640|
|6|2251|5377|
|7|2597|6752|
|8|2955|N/A|
|9|3553|N/A|
|10|4960|N/A|
|11|6090|N/A|
|12|7556|N/A|


